jummy:
  mysql:
    ip: 127.0.0.1
    port: 3306
    database: jsoa
    username: root
    password: 123456
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true


spring:
  main:
    #    避免组件bean重复
    allow-bean-definition-overriding: true
  application:
    name: json-boot-server
  profiles:
    active: jummy
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      enable: true
      username: ${jummy.mysql.username}
      password: ${jummy.mysql.password}
      url: jdbc:mysql://${jummy.mysql.ip}:${jummy.mysql.port}/${jummy.mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
      db-type: mysql
      initial-size: 10
      min-idle: 10
      max-active: 200
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
      filter:
        wall:
          enabled: true
          config:
            commentAllow: true
            multiStatementAllow: true
            noneBaseStatementAllow: true
      # 从这里结束(druid)，中间的这段配置用于 lamp.database.multiTenantType != DATASOURCE 时
      web-stat-filter:  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        reset-enable: true    #允许清空统计数据
        login-username: jummy
        login-password: jummy

logging:
  path: /Users/jummy/IdeaProjects/jsoa/logs

# 用于/actuator/info
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '1.0-SNAPSHOT'
  spring-boot-version: '2.1.2.RELEASE'
  spring-cloud-version: 'Greenwich.RELEASE'
server:
  port: 8080

